// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package webui provides a sublauncher that adds ADK Web UI capabilities.
package webui

import (
	"bytes"
	"embed"
	"flag"
	"fmt"
	"html"
	"io/fs"
	"log"
	"net/http"
	"path"
	"regexp"
	"strings"
	"time"

	"github.com/gorilla/mux"

	"google.golang.org/adk/v2/cmd/launcher"
	weblauncher "google.golang.org/adk/v2/cmd/launcher/web"
	"google.golang.org/adk/v2/internal/cli/util"
	"google.golang.org/adk/v2/server/adkrest/controllers"
)

// webUIConfig contains parameters for launching ADK Web UI
type webUIConfig struct {
	backendAddress string
	pathPrefix     string
}

// webUILauncher can launch ADK Web UI
type webUILauncher struct {
	flags  *flag.FlagSet
	config *webUIConfig
}

// CommandLineSyntax implements web.Sublauncher. Returns the command-line syntax for the WebUI launcher.
func (w *webUILauncher) CommandLineSyntax() string {
	return util.FormatFlagUsage(w.flags)
}

// Keyword implements web.Sublauncher. Returns the command-line keyword for WebUI launcher.
func (w *webUILauncher) Keyword() string {
	return "webui"
}

// Parse implements web.Sublauncher. After parsing webui-specific arguments returns remaining unparsed arguments
func (w *webUILauncher) Parse(args []string) ([]string, error) {
	err := w.flags.Parse(args)
	if err != nil || !w.flags.Parsed() {
		return nil, fmt.Errorf("failed to parse webui flags: %v", err)
	}
	restArgs := w.flags.Args()
	return restArgs, nil
}

// SetupSubrouters implements the web.Sublauncher interface. It adds the
// WebUI subrouter to the main router.
func (w *webUILauncher) SetupSubrouters(router *mux.Router, config *launcher.Config) error {
	w.AddSubrouter(router, w.config.pathPrefix, w.config.backendAddress)
	return nil
}

// SimpleDescription returns a simple description of the WebUI launcher.
func (w *webUILauncher) SimpleDescription() string {
	return "starts ADK Web UI server which provides UI for interacting with ADK REST API"
}

// UserMessage implements the web.Sublauncher interface. It prints a message
// to the user with the URL to access the WebUI.
func (w *webUILauncher) UserMessage(webURL string, printer func(v ...any)) {
	printer(fmt.Sprintf("       webui:  you can access API using %s%s", webURL, w.config.pathPrefix))
}

// embed web UI files into the executable

//go:embed distr/*
var content embed.FS

// indexFile is the single-page app entry point inside the embedded bundle.
const indexFile = "index.html"

// baseHrefPattern matches the Angular <base href="..."> tag, whatever its
// spacing and attribute order. The pattern is deliberately tolerant because the
// bundle is regenerated by the Angular build, which is free to reformat it.
var baseHrefPattern = regexp.MustCompile(`(?is)<base\s[^>]*?href\s*=\s*"[^"]*"`)

// noListingFS reports a directory without an index.html as missing.
//
// http.FileServer renders an HTML directory listing for such a directory, which
// leaks the bundle layout (/ui/assets/config/ listed runtime-config.json).
// Directories that do have an index.html are left alone, since that is how the
// UI root itself is served.
type noListingFS struct {
	fsys fs.FS
}

// Open implements fs.FS.
func (n noListingFS) Open(name string) (fs.File, error) {
	f, err := n.fsys.Open(name)
	if err != nil {
		return nil, err
	}
	info, err := f.Stat()
	if err != nil {
		return nil, errAfterClose(f, err)
	}
	if info.IsDir() && !hasIndex(n.fsys, name) {
		return nil, errAfterClose(f, &fs.PathError{Op: "open", Path: name, Err: fs.ErrNotExist})
	}
	return f, nil
}

// errAfterClose closes f and returns err, joined with any close failure.
func errAfterClose(f fs.File, err error) error {
	if closeErr := f.Close(); closeErr != nil {
		return fmt.Errorf("%w (and closing the file failed: %w)", err, closeErr)
	}
	return err
}

// hasIndex reports whether dir contains an index.html.
func hasIndex(fsys fs.FS, dir string) bool {
	_, err := fs.Stat(fsys, path.Join(dir, indexFile))
	return err == nil
}

// spaHandler serves the Angular single-page app out of the embedded bundle.
//
// A request that matches no file is answered with index.html so that deep links
// such as /ui/eval survive a refresh or a bookmark, but only when it has no file
// extension: answering a missing .js or .css with HTML turns a clear 404 into a
// syntax error somewhere inside the browser, which is far harder to diagnose.
type spaHandler struct {
	files      fs.FS
	prefix     string
	index      []byte
	fileServer http.Handler
}

// ServeHTTP implements http.Handler.
func (h *spaHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	name := h.fsPath(r.URL.Path)
	info, err := fs.Stat(h.files, name)
	switch {
	case err == nil && info.IsDir():
		// noListingFS turns every other directory into a 404, so a directory is
		// only ever served as its index.html - which needs the rewritten
		// <base href> just as much as a deep link does.
		if hasIndex(h.files, name) {
			h.serveIndex(w, r)
			return
		}
	case err != nil && path.Ext(name) == "":
		h.serveIndex(w, r)
		return
	}
	h.fileServer.ServeHTTP(w, r)
}

// fsPath maps a request path to a path inside the embedded bundle. Cleaning the
// path keeps "../" from reaching outside the bundle.
func (h *spaHandler) fsPath(urlPath string) string {
	rel := path.Clean("/" + strings.TrimPrefix(urlPath, h.prefix))[1:]
	if rel == "" {
		return "."
	}
	return rel
}

// serveIndex writes the cached index.html. ServeContent derives the content type
// from the name and handles HEAD and Range for us. The zero modification time
// suppresses Last-Modified, which an embedded file system cannot supply.
func (h *spaHandler) serveIndex(w http.ResponseWriter, r *http.Request) {
	http.ServeContent(w, r, indexFile, time.Time{}, bytes.NewReader(h.index))
}

// rewriteBaseHref points the <base href> of index.html at pathPrefix.
//
// The bundle ships with href="./", which resolves assets against the directory
// of the *request*. Serving that file for /ui/a/b/c would send the browser
// looking for /ui/a/b/polyfills-*.js and every asset would 404, leaving a blank
// page - worse than the honest 404 the fallback replaced. It only appears to
// work one level deep, where "./" happens to still mean the prefix.
func rewriteBaseHref(indexHTML []byte, pathPrefix string) []byte {
	if !baseHrefPattern.Match(indexHTML) {
		log.Printf("ADK Web UI: no <base href> found in %s, deep links may fail to load assets", indexFile)
		return indexHTML
	}
	replacement := []byte(`<base href="` + html.EscapeString(pathPrefix) + `"`)
	return baseHrefPattern.ReplaceAllLiteral(indexHTML, replacement)
}

// AddSubrouter adds a subrouter to serve the ADK Web UI.
func (w *webUILauncher) AddSubrouter(router *mux.Router, pathPrefix, backendAddress string) {
	// Setup serving of ADK Web UI. HEAD is accepted everywhere GET is: probes
	// and link checkers use it, and http.FileServer already answers it
	// correctly, so refusing it with a 405 gained nothing.
	uiMethods := []string{http.MethodGet, http.MethodHead}
	rUI := router.Methods(uiMethods...).PathPrefix(pathPrefix).Subrouter()

	//   generate /assets/config/runtime-config.json in the runtime.
	//   It removes the need to prepare this file during deployment and update the distribution files.
	runtimeConfigResponse := struct {
		BackendUrl string `json:"backendUrl"`
	}{BackendUrl: backendAddress}
	rUI.Methods(uiMethods...).Path("/assets/config/runtime-config.json").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		controllers.EncodeJSONResponse(runtimeConfigResponse, http.StatusOK, w)
	})

	//   redirect the user from / to pathPrefix (/ui/)
	router.Methods(uiMethods...).Path("/").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, pathPrefix, http.StatusFound)
	})

	//   send the bare prefix (/ui) to the prefix proper (/ui/), which is all the
	//   PathPrefix subrouter below matches.
	//
	//   The base router runs with StrictSlash(true), under which Path("/ui")
	//   compiles to ^/ui[/]?$ and so also matches /ui/, bouncing it back to /ui
	//   for an endless redirect. An exact-equality matcher cannot match the
	//   trailing-slash form, so the loop cannot form.
	if bare := strings.TrimSuffix(pathPrefix, "/"); bare != "" {
		router.Methods(uiMethods...).
			MatcherFunc(func(r *http.Request, _ *mux.RouteMatch) bool {
				return r.URL.Path == bare
			}).
			HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				http.Redirect(w, r, pathPrefix, http.StatusMovedPermanently)
			})
	}

	// serve web ui from the embedded resources
	ui, err := fs.Sub(content, "distr")
	if err != nil {
		log.Fatalf("cannot prepare ADK Web UI files as embedded content: %v", err)
	}
	indexHTML, err := fs.ReadFile(ui, indexFile)
	if err != nil {
		log.Fatalf("cannot read %s from the embedded ADK Web UI files: %v", indexFile, err)
	}
	// Rewrite once at setup: index.html is ~53KB and every deep link serves it.
	rUI.Methods(uiMethods...).Handler(&spaHandler{
		files:      ui,
		prefix:     pathPrefix,
		index:      rewriteBaseHref(indexHTML, pathPrefix),
		fileServer: http.StripPrefix(pathPrefix, http.FileServer(http.FS(noListingFS{fsys: ui}))),
	})
}

// NewLauncher creates a new Sublauncher for the ADK Web UI.
func NewLauncher() weblauncher.Sublauncher {
	config := &webUIConfig{}

	fs := flag.NewFlagSet("webui", flag.ContinueOnError)
	fs.StringVar(&config.backendAddress, "api_server_address", "http://localhost:8080/api", "ADK REST API server address as seen from the user browser. Please specify the whole URL, i.e. 'http://localhost:8080/api'.")
	config.pathPrefix = "/ui/"

	return &webUILauncher{
		config: config,
		flags:  fs,
	}
}
