// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package session

import (
	"context"
	"errors"
	"time"
)

// ErrNotFound reports that the requested session does not exist.
//
// Every [Service] implementation wraps it from [Service.Get] and from
// [Service.AppendEvent] when the session named in the request is absent, so
// that a caller can tell a missing session from a storage failure:
//
//	if errors.Is(err, session.ErrNotFound) { … }
//
// No other method reports it, because no other method treats a missing session
// as a failure: [Service.Delete] is a no-op on one, and [Service.List] returns
// an empty result. Nor does it cover every error those two methods can return.
// A request that names a session belonging to another user, one that fails
// validation, and a backend that is simply unreachable all stay ordinary
// errors, so errors.Is never reads "not yours", "not valid" or "not working"
// as "not there".
//
// The REST layer relies on this to answer 404 rather than 500. Wrap it first,
// as fmt.Errorf("%w: …: %w", session.ErrNotFound, err).
var ErrNotFound = errors.New("session not found")

// Service is a session storage service.
//
// It provides a set of methods for managing sessions and events.
type Service interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Delete(context.Context, *DeleteRequest) error
	// AppendEvent is used to append an event to a session, and remove temporary state keys from the event.
	//
	// Two further obligations, both checked by the shared conformance suite in
	// session/sessiontestsuite, so an implementation that misses either goes
	// red there rather than failing quietly in production:
	//
	// An event arriving with no ID must end up with one. Events built as struct
	// literals by an agent or a tool never pass through [NewEvent] and arrive
	// unnamed, and a stored event that cannot be named cannot be referred to by
	// anything that identifies events by ID.
	//
	// Where the implementation assigns the ID itself, it must be on the
	// caller's event, in place. Where the server assigns it, the ID appears on
	// the event when it is read back instead, and the conformance suite waives
	// the in-place half for those: session/vertexai is one, and it does not
	// assign in place. What holds everywhere is that the stored event has an
	// ID, which the suite checks on the read either way.
	//
	// [EventActions.Compaction] must survive the round trip. A context
	// compaction summary carries its content only there: LLMResponse.Content is
	// nil and there is no state or artifact delta, so a backend that decides
	// what to persist by looking at content or deltas drops it without
	// complaint. The session then comes back with no summary and no record that
	// compaction ran, and the same range is summarized and billed again on
	// every later turn.
	AppendEvent(context.Context, Session, *Event) error
}

// InMemoryService returns an in-memory implementation of the session service.
func InMemoryService() Service {
	return &inMemoryService{
		appState:  make(map[string]stateMap),
		userState: make(map[string]map[string]stateMap),
	}
}

// CreateRequest represents a request to create a session.
type CreateRequest struct {
	AppName string
	UserID  string
	// SessionID is the client-provided ID of the session to create.
	// Optional: if not set, it will be autogenerated.
	SessionID string
	// State is the initial state of the session.
	State map[string]any
}

// CreateResponse represents a response for newly created session.
type CreateResponse struct {
	Session Session
}

// GetRequest represents a request to get a session.
type GetRequest struct {
	AppName   string
	UserID    string
	SessionID string

	// NumRecentEvents returns at most NumRecentEvents most recent events.
	// Optional: if zero, the filter is not applied.
	NumRecentEvents int
	// After returns events with timestamp >= the given time.
	// Optional: if zero, the filter is not applied.
	After time.Time
}

// GetResponse represents a response from [Service.Get].
type GetResponse struct {
	Session Session
}

// ListRequest represents a request to list sessions.
type ListRequest struct {
	AppName string
	UserID  string
}

// ListResponse represents a response from [Service.List].
type ListResponse struct {
	Sessions []Session
}

// DeleteRequest represents a request to delete a session.
type DeleteRequest struct {
	AppName   string
	UserID    string
	SessionID string
}
